openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the RAG chatbot embedded in the Docusaurus book
  version: 1.0.0
servers:
  - url: https://api.rag-chatbot.example.com
    description: Production server
  - url: https://staging-api.rag-chatbot.example.com
    description: Staging server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-12-11T10:00:00Z"

  /ingest:
    post:
      summary: Ingest book content
      description: Parse and store book content for RAG retrieval
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_url:
                  type: string
                  description: URL to the Docusaurus book content
                  example: "https://q4-hackathon-eosin.vercel.app"
                force_reprocess:
                  type: boolean
                  description: Whether to force reprocessing of existing content
                  example: false
              required:
                - source_url
      responses:
        '200':
          description: Content successfully ingested
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Content successfully ingested"
                  documents_processed:
                    type: integer
                    example: 25
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /chat:
    post:
      summary: Handle general queries with history
      description: Process user queries against the full knowledge base
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: User's query message
                  example: "What are the key concepts in humanoid robotics?"
                conversation_id:
                  type: string
                  description: Optional conversation ID for maintaining context
                  example: "abc123-uuid"
                user_session:
                  type: string
                  description: User session identifier
                  example: "user-session-123"
              required:
                - message
      responses:
        '200':
          description: Query processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    example: "abc123-uuid"
                  response:
                    type: string
                    example: "Humanoid robotics involves..."
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        url:
                          type: string
                        section:
                          type: string
                  sources:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /chat/selection:
    post:
      summary: Handle selected text queries
      description: Process user queries with selected text as additional context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: User's query message
                  example: "Can you explain this concept further?"
                selected_text:
                  type: string
                  description: Text selected by the user in the book
                  example: "Humanoid robots are robots with human-like characteristics..."
                conversation_id:
                  type: string
                  description: Optional conversation ID for maintaining context
                  example: "abc123-uuid"
                user_session:
                  type: string
                  description: User session identifier
                  example: "user-session-123"
              required:
                - message
                - selected_text
      responses:
        '200':
          description: Query processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    example: "abc123-uuid"
                  response:
                    type: string
                    example: "Based on the selected text and related concepts..."
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        url:
                          type: string
                        section:
                          type: string
                  sources:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error