from typing import List, Dict, Any
from ..services.embedding_service import embedding_service
from ..services.qdrant_service import qdrant_service
from ..utils.settings import settings


class RAGService:
    def __init__(self):
        self.qdrant_service = qdrant_service
        self.embedding_service = embedding_service

    def retrieve_relevant_content(
        self,
        query: str,
        top_k: int = 5,
        score_threshold: float = 0.7
    ) -> List[Dict[str, Any]]:
        """
        General retrieval logic for finding relevant content based on the query
        """
        # Generate embedding for the query
        query_embedding = self.embedding_service.embed_single_text(query, input_type="search_query")

        # Search in Qdrant
        results = self.qdrant_service.search_vectors(
            query_vector=query_embedding,
            top_k=top_k,
            score_threshold=score_threshold
        )

        return results

    def retrieve_with_selection_context(
        self,
        query: str,
        selected_text: str,
        top_k: int = 3
    ) -> List[Dict[str, Any]]:
        """
        Selection-based retrieval logic that combines selected text with additional context
        """
        # Use the selected text as primary context
        primary_result = {
            "content": selected_text,
            "module": "selected_text",
            "section": "user_selection",
            "url": "user_selection",
            "score": 1.0  # Highest relevance for selected text
        }

        # Create a combined query to find related content
        combined_query = f"{query} {selected_text}"
        related_results = self.retrieve_relevant_content(
            combined_query,
            top_k=top_k,
            score_threshold=0.5  # Slightly lower threshold for supplementary content
        )

        # Return primary context plus related results
        return [primary_result] + related_results

    def generate_response_with_context(
        self,
        query: str,
        context_chunks: List[Dict[str, Any]]
    ) -> str:
        """
        Generate a response using the provided context chunks
        This would typically call the agent service, but for now we'll return a formatted response
        """
        # Format context for response generation
        context_str = "\n\n".join([
            f"Module: {chunk['module']}\nSection: {chunk['section']}\nContent: {chunk['content']}\n"
            for chunk in context_chunks
        ])

        # This is a placeholder - in the full implementation, this would call the agent service
        response = f"Based on the provided context:\n\n{context_str}\n\nQuery: {query}\n\nResponse: [This would be generated by the agent using the context and query]"
        return response


# Global instance
rag_service = RAGService()